### ISSUE TITLE
I cannot find Musyc_demo.exe

### ISSUE THREAD

**Issue by DJuarez10** [QuLab-VU/MuSyC_Cell#6]
Is Musyc_demo.exe not currently available?

**Comment by meyerct1** [comment]
Hey DJuarez10.  Sorry for the lag in response. Are you trying to fit data or just want to visualize how the different parameters change the shape of the dose-response surface?

**Comment by DJuarez10** [comment]
Hi Christian,

Beautiful work, first off. From users of Chou Talalay's software for
assessing synergy, the distinction between synergistic efficacy and
synergistic potency that MuSyc incorporates is a very important
consideration for anyone assessing synergy. I ultimately want to apply this
synergy model for my research, but before doing that I want to have a
better understanding of the model, so yes I would like to visualize how
different parameters change the shape of the dose-response model.

My research focuses on improving venetoclax efficacy in Multiple Myeloma, a
disease where drug combinations are the standard of care. We have
combinations that we would like to assess for synergy, but since we use
drugs like glucocorticoids, Chou Talalay is limited by differences in drug
efficacy. Also, we are interested in assessing triple combinations, and no
offense to Chou Talalay, but polygonograms aren't the most elegant solution
to describe multidrug combinations. This is why I'm interested in applying
MuSyc to my work.

Best,
Dennis

**Comment by DJuarez10** [comment]
Christian,

I've figured out how to load the demo now using MatLab. I was just confused about the lack of exe file.

Thanks!
